name: packed
description: CLI to generate Flutter feature structure
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  packed: packed