name: packed
description: A CLI tool to rapidly generate Flutter feature structures following the BLoC pattern.
version: 0.1.2
repository: https://github.com/Ahmedx44/packed
homepage: https://github.com/Ahmedx44/packed

environment:
  sdk: ^3.10.1

dependencies:
  path: ^1.9.0
  args: ^2.4.2 

executables:
  packed: packed